### ISSUE TITLE
build script is not working

### ISSUE THREAD

**Issue by panweizhong** [Wind-River/vxworks7-layer-for-ros2#1]
follow the instructions https://github.com/Wind-River/vxworks7-ros2-build
1.	git clone https://github.com/Wind-River/vxworks7-ros2-build
2.	 cd vxworks7-ros2-build/
3.	 sudo make INSTALL_DIR=/opt/VX7S620 WORKSPACE=/home/wpan/workspace
it will reprot the following error:
checking for x86_64-wrs-vxworks-gcc... /opt/VX7S620/compilers/llvm-8.0.0.1/LINUX64/bin/clang
checking whether the C compiler works... no
configure: error: in `/home/wpan/workspace/up_ros2small_vsb/3pp/ASIO/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
/opt/VX7S620/vxworks-7/build/mk/usr/rules.packages.mk:319: recipe for target 'asio.configure' failed
make[4]: *** [asio.configure] Error 77
make[4]: Leaving directory '/home/wpan/workspace/up_ros2small_vsb/3pp/ASIO/build'
/opt/VX7S620/vxworks-7/build/mk/usr/rules.packages.mk:48: recipe for target 'postbuild' failed
make[3]: *** [postbuild] Error 2
make[3]: Leaving directory '/opt/VX7S620/vxworks-7/pkgs_v2/middleware/asio/user_src'
__layer_prebuild_ASIO.mk:77: recipe for target 'ASIO_user_src_llvm__POSTBUILD' failed
make[2]: *** [ASIO_user_src_llvm__POSTBUILD] Error 2
make[2]: Leaving directory '/home/wpan/workspace/up_ros2small_vsb/mk'
/opt/VX7S620/vxworks-7/build/mk/krnl/rules.vsb.mk:335: recipe for target 'POSTBUILD' failed
make[1]: *** [POSTBUILD] Error 2
make[1]: Leaving directory '/home/wpan/workspace/up_ros2small_vsb'
ASIO build failed :
child process exited abnormally
+ '[' '!' -f 3pp/.stamp/asio.install ']'
+ echo 'Could not build layer ASIO'
Could not build layer ASIO
+ exit 1
## ERROR: /home/wpan/ros/vxworks7-ros2-build/scripts/prj-build.sh
Makefile:70: recipe for target 'prj.build' failed
make: *** [prj.build] Error 1

**Comment by rcwoolley** [comment]
Thanks for filing the issue.  In VxWorks 7 SR0620 some changes were made to the linker variables that get exported in the vxworks_env.sh script.

This results in the linker script appearing twice (ie. -T/home/rcwoolley/asiofault/up_ros2small_vsb/usr/ldscripts/rtp.ld) and results in an internal error in the linker.

We have a development branch ready for SR0620.  You may access it by setting a branch when doing the git clone in the first step:

git clone -b dashing-release-SR0620 https://github.com/Wind-River/vxworks7-ros2-build

We plan to merge this development branch into master soon.
